# Generated by Django 3.2.7 on 2021-09-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_auto_20210916_1425'),
        ('datawork', '0002_auto_20210916_1429'),
    ]

    operations = [
    ]
